### ISSUE TITLE
3주차 스프링 스터디  (21.01.05 ~ 21.01.11)

### ISSUE THREAD

**Issue by Parkyunhwan** [Hott-J/Spring-Study#17]
# :book: 3주차 스프링 스터디  (21.01.05 ~ 21.01.11)

## TodoList

- **_Petclinic_** 전부 다 듣고, 실습코드 올리고 본인 폴더에 공부내용 정리
- 각 챕터별로 `PR` 만든뒤, 한 챕터당 여러개 `PR` 이어붙이기
  - 해당 강의 별로 각자 간단히 `Comment` 달고, 나머지 사람들은 `코드 리뷰` 해주기
  -  코드 리뷰 후 상대방의 `PR`을 `Approve` 하기  👉 [[Approve 방법]](https://github.com/im-d-team/Dev-Docs/issues/11)
 
## 2주차 스터디 내용 정리

  - [x] **학제 : html 태그와 memberForm, memberController 동작 순서와 원리 정리**
  - [x] **승수 : 프록시 개념 및 동작 원리 정리. AOP와 연관지어 설명할 것**
  - [x] **윤환 : dto, dao, entity 클래스 설명하기**
  - [x] **재훈 : view resolver 와 converter. 스터디에서 이야기했던 그림에는 컨버터가 아니라 뷰 리졸버만 있었는데, 컨버터는 어디에 위치하는지**
  - [x] **경원 : 순환참조. 의존성주입과 관련지어 설명할 것**

**Comment by Hott-J** [comment]
finish
