### ISSUE TITLE
 4주차 스프링 스터디

### ISSUE THREAD

**Issue by Parkyunhwan** [Hott-J/Spring-Study#33]
# :book: 4주차 스프링 스터디  (21.01.12 ~ 21.01.18)

## TodoList

- **Restful 강의  >> 섹션 3. RESTful Service 기능 확장**  까지 듣고 정리하기
- 각 챕터별로 `PR` 만든뒤, 한 챕터당 여러개 `PR` 이어붙이기
  - 해당 강의 별로 각자 간단히 `Comment` 달고, 나머지 사람들은 `코드 리뷰` 해주기
  -  코드 리뷰 후 상대방의 `PR`을 `Approve` 하기  👉 [[Approve 방법]](https://github.com/im-d-team/Dev-Docs/issues/11)
  -  마지막 `Approve` 한 사람이 pull request 닫아주기
 
## 3주차 스터디 내용 정리

  - [x] **학제 : 질문 사항 정리하기**
  - [x] **승수 : 저녁으로 응원 해주기**
  - [x] **윤환 : 많이 쓰이는 어노테이션 정리**
  - [x] **재훈 : 서블릿에 대한 개념**
  - [x] **경원 : PetClinic 분석하기**

**Comment by Kyeong-Won** [comment]
URI와 URL의 차이점 알아오겠습니다.

**Comment by Parkyunhwan** [comment]
Finish.
